version: '3.7'

services:
  db:
    container_name: postgres
    image: postgres:14.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'order_storage'
    env_file:
      - ./.env
    ports:
      - 5432:5432

  web:
    container_name: web
    build:
      target: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  updater:
    container_name: updater
    build:
      target: django
    command: python manage.py watch
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  db_data:
