# Generated by Django 4.1 on 2022-08-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер заказа')),
                ('usd_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rub_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_date', models.DateField(verbose_name='Дата поставки')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='Срок истек')),
                ('expiration_message_sent', models.BooleanField(default=False, verbose_name='Уведомление о просрочке отправлено')),
            ],
        ),
    ]
